[project]
name = "autoconf"
version = "0.0.1"
authors = [
    { name="Jason Wilkes", email="notarealdeveloper@gmail.com" },
]
description = "A minimal example of autoconfiguration for python"
dependencies = [
]

[project.urls]
source = "https://github.com/notarealdeveloper/autoconf"
